"""empty message

Revision ID: e2c1f23e2ca6
Revises: 296593e270ee
Create Date: 2017-09-23 10:48:33.750307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2c1f23e2ca6'
down_revision = '296593e270ee'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('users', 'vk',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'vk',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    ### end Alembic commands ###
